name: example
on: push
jobs:
  greeting: 
    runs-on: ubuntu-latest
    steps:
      - name: Print hello  
        run: echo hello world
  build_skim:
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        run: |
          COMPILER=$(root-config --cxx)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx

